export const ListSearch = [
  "iPhone 16",
  "iPhone 16 Pro",
  "iPhone 16 Pro Max",
  "iPhone 16 Plus",
  "iPhone 16 128gb",
  "airpods 4",
  "iphone 15",
  "iphone 15 128gb",
  "iphone 15 plus",
  "iphone 15 pro",
  "iphone 15 pro max",
  "tai nghe Airpods",
  "tai nghe iphone",
  "tai nghe Shokz",
  "macbook air m3",
  "orient star",
  "macbook air m3 15 inch",
  "macbook",
  "macbook pro m3",
  "apple watch",
  "apple watch se 2023",
  "apple watch ultra 2",
  "apple watch series 9",
  "S24 ultra",
  "iPad Pro M4",
  "Loa Marshall",
  "Sony WF-C500",
  "tai nghe Sony",
  "sạc Baseus",
  "cáp Baseus",
  "tai nghe JBL",
  "samsung galaxy watch 7",
  "đồng hồ Edox",
  "tai nghe Shokz",
  "Đồng hồ Movado",
  "Laptop",
  "Loa",
  "Tai nghe",
  "Đồng hồ thời trang",
];
